"""empty message

Revision ID: 60548ddecf5c
Revises: 
Create Date: 2025-03-07 02:33:48.114180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60548ddecf5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('items', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
